### ISSUE TITLE
mvn exec:java failed

### ISSUE THREAD

**Issue by stephankokkas** [corsoft/esper-demo-nuclear#3]
![Screen Shot 2022-09-05 at 9 45 01 pm](https://user-images.githubusercontent.com/3150898/188441486-11cb921c-0406-4cb4-afc6-964a04beeee4.png)

**Comment by stephankokkas** [comment]
BUILD SUCCESS if you change lines 95 and 96 in pom.xml to 
```
<source>1.8</source>
<target>1.8</target>
```

**Comment by stephankokkas** [comment]
The above comment fixed the issue of the ```mvn clean install```. However, ```mvn exec:java``` is still failing. 

It seems to get to _create Critical Temperature Check Expression_ but fails with the below error codes:

[BUILD FAILED.txt](https://github.com/adrianmilne/esper-demo-nuclear/files/9489585/BUILD.FAILED.txt)

**Comment by AlexLu0419** [comment]
You might be using a higher JDK version that is not compatible with this project. Try to downgrade your JDK.
